### ISSUE TITLE
Optimize for 1920x1080

### ISSUE THREAD

**Issue by CmdSoda** [iebb/F1Manager-Calc#1]
Thank you for this great app. Can you take care that the all relevant information is always visible on a 1920x1080 setup without being forced to scroll up and down. A lot of space is wasted for the big title on the top. I need to scroll down a bit see what is really relevant for me.

**Comment by Beanow** [comment]
I assume you mean, once you've added some feedback it just goes off screen.

I'm on 1440p, so I tried a 1920x900 viewport, assuming some space used by tabs, URL bar, etc.
I think being able to hide the usage tips, might *just* do the trick for 1080p?

What do you think?

![Screen Shot 2022-08-28 at 11 55 12](https://user-images.githubusercontent.com/497556/187068240-63f093fd-e820-4ea7-913b-0997a5bbd2ce.png)
![Screen Shot 2022-08-28 at 11 55 08](https://user-images.githubusercontent.com/497556/187068242-34a51d73-984f-491d-a4f9-16303732195e.png)

**Comment by CmdSoda** [comment]
Looks much better!

**Comment by iebb** [comment]
> I assume you mean, once you've added some feedback it just goes off screen.
> 
> I'm on 1440p, so I tried a 1920x900 viewport, assuming some space used by tabs, URL bar, etc. I think being able to hide the usage tips, might _just_ do the trick for 1080p?
> 
> What do you think?
> 
> ![Screen Shot 2022-08-28 at 11 55 12](https://user-images.githubusercontent.com/497556/187068240-63f093fd-e820-4ea7-913b-0997a5bbd2ce.png) ![Screen Shot 2022-08-28 at 11 55 08](https://user-images.githubusercontent.com/497556/187068242-34a51d73-984f-491d-a4f9-16303732195e.png)

Might be a good idea

**Comment by CmdSoda** [comment]
Looks good for me now.
