### ISSUE TITLE
0 Setups possible 

### ISSUE THREAD

**Issue by Beanow** [iebb/F1Manager-Calc#2]
On a few runs now I've wound up with 0 Setups Possible. And the setups go from high 90s to low 90s or worse.

My _suspicion_ after a few attempts is that having multiple "optimal" feedback on the same bias type causes this.
If, with the remaining stints you're able to eliminate the problematic "optimal" feedback you can still get 100%, other times I just need to settle for reverting to a 93%.

Now I notice you've just tweak the values here:
https://github.com/iebb/F1Manager-Calc/blob/77917d6401e2c98dd99660b8484ea97b0fc331db/pages/index.js#L47-L50

And I've just now refreshed to include this change. Could that already have fixed the issue?

**Comment by iebb** [comment]
If you have more accurate breakpoints for these values please tell me, from the data I gathered it seems to be -
< 0.0075 for optimal (not sure about it, however it should between 0.00625 and 0.008)
< 0.04 for great
< 0.1 for good

**Comment by Beanow** [comment]
I've not looked too deeply into the calculations yet, or tried other values. If I hit another 0 Setups run, I'll try changing these parameters around.

But am I right to assume that these "breakpoints" define how wide the optimal/great/good regions are?
As I suspect the optimal zone might be too narrow currently.

**Comment by Beanow** [comment]
Here's one sample, I'll try find a bit more about. (3rd stint atm so room to do more runs.)
![image](https://user-images.githubusercontent.com/497556/187651592-d59db4e0-2891-4e5b-a78f-e45324277c0d.png)

**Comment by Beanow** [comment]
And the same issue for the other car.
Still collecting data and trying things out.
![image](https://user-images.githubusercontent.com/497556/187683286-646a5965-d018-44e9-9b3f-1c9e8a867f91.png)

**Comment by iebb** [comment]
Ok problem solved, just found a rounding issue which prevents approaching the maximal value, which ignores all such setups.
nvm just have it fixed

https://github.com/iebb/F1Manager-Calc/blob/8af633b4ba36def584d3031af654245bb1736e1b/pages/index.js#L151-L152

**Comment by Beanow** [comment]
Correct sir! I think that did fix the issue. Both driver's setups required Tyre Camber `-3.50` and looks like that wasn't considered before.

This is the complete sampling I did for the run, if you need any test data :sweat_smile:
(Made a save file after P1, and well... did a lot of runs)

## Car 1 (Gasly)

![image](https://user-images.githubusercontent.com/497556/187727265-b9dd7118-d794-43ce-b2bc-52dfd17e09c7.png)

## Car 2 (Tsunoda)

![image](https://user-images.githubusercontent.com/497556/187727424-5926cdd5-b4d7-42d7-a63b-fd6433a5427c.png)

**Comment by iebb** [comment]
> If you have more accurate breakpoints for these values please tell me, from the data I gathered it seems to be - < 0.0075 for optimal (not sure about it, however it should between 0.00625 and 0.008) < 0.04 for great < 0.1 for good

This is figured out by lots of attempts:
optimal: <= 39/5600 = 0.0069642857142857145, 0.007 could be used as an alternative

**Comment by Beanow** [comment]
Ha well all my experimentation with breakpoints was invalidated. Because the correct solution wasn't in the search set.

Could have a look at using the eventual solution into a smoke test :shrug:
