### ISSUE TITLE
env template for MongoDB

### ISSUE THREAD

**Issue by manuelkamp** [iebb/F1Manager-Calc#7]
can you add a template for .env regarding addition for a mongodb for cloud sync?

**Comment by iebb** [comment]
anything would work. it's schemaless, you can just have one from Atlas

**Comment by manuelkamp** [comment]
well, anything would simply not work. try this as env and tell me if it works:

```
ANYTHING="tryme"
SOMETHING="lalala"
```

For everyone else, this specific env template would work:
NEXTAUTH_SECRET: Copy-paste the output of `openssl rand -base64 32`
NEXTAUTH_URL: Change to your FQDN where yout F1 Manager calculator runs
DISCORD_CLIENT_ID: Navigate to: https://discord.com/developers/applications and create new application. In OAuth2 section you get CLIENT ID to fill in here.
DISCORD_CLIENT_SECRET: In the same OAuth2 section described above you also get CLIENT SECRET to fill in here.

```
AUTH_DATABASE_NAME="f1setup"
NEXTAUTH_SECRET=""
NEXTAUTH_URL="https://f1setup.yourdomain"
DISCORD_CLIENT_ID=""
DISCORD_CLIENT_SECRET=""
MONGODB_URI="mongodb://localhost:27017"
```

**Comment by iebb** [comment]
Sorry, I just mean that any valid mongodb connection strings would work for the URI thing; 

I'm also planning to make the MongoDB part optional (or on a separate project) if people want to take part in the development or want to fork/self-host it.
